export const CAREERS_CONTENT = {
  eyebrow: 'Join Our Global Talent Pods',
  badge: 'Active Recruitment',
  title: 'Build an Impactful Career with Global Industry Leaders',
  subtitle: 'We empower ambitious professionals with international exposure, continuous skills development, and world-class work environments.',
  intro: [
    'At Your Source Global (YSG), we believe that superior client outcomes begin with exceptional employee experiences. Our delivery centers in the Philippines and regional offices in the US and UAE are designed to foster professional growth, cross-cultural collaboration, and high-standard operational excellence.',
    'Join dedicated client pods where your expertise directly shapes the success of high-growth international businesses across finance, technology, customer operations, and healthcare.',
  ],
  cultureHighlights: [
    {
      title: 'Global Career Trajectory',
      desc: 'Collaborate directly with executive teams across North America, the UAE, and APAC.',
      icon: 'Compass',
    },
    {
      title: 'Competitive Rewards & Healthcare',
      desc: 'Comprehensive HMO coverage, performance bonuses, and career milestone incentives.',
      icon: 'HeartHandshake',
    },
    {
      title: 'Continuous Skill Acceleration',
      desc: 'Structured training programs covering modern enterprise software, GAAP standards, and IT tooling.',
      icon: 'GraduationCap',
    },
    {
      title: 'Modern Ergonomic Facilities',
      desc: 'High-speed redundant infrastructure, collaborative lounges, and wellbeing amenities.',
      icon: 'Building2',
    },
  ],
  openRoles: [
    {
      id: 'finance-lead',
      title: 'Senior Financial Analyst & Bookkeeper',
      department: 'Finance & Accounting',
      type: 'Full-Time',
      location: 'Manila Hub / Hybrid',
      shift: 'US Eastern Shift',
      description: 'Manage general ledger, multi-currency reconciliations, and financial reporting workflows for US enterprise clients.',
      requirements: ['3+ years GAAP / QuickBooks / NetSuite experience', 'Strong analytical and spreadsheet modeling skills'],
    },
    {
      id: 'support-team-lead',
      title: 'Omnichannel Customer Support Specialist',
      department: 'Customer Care Operations',
      type: 'Full-Time',
      location: 'Manila Hub',
      shift: '24/7 Shift Rotation',
      description: 'Deliver first-contact resolution across email, live chat, and voice channels with strict SLA adherence.',
      requirements: ['2+ years Zendesk / Salesforce Service Cloud', 'Exceptional written & spoken English communication'],
    },
    {
      id: 'ap-ar-officer',
      title: 'Accounts Payable / Receivable Specialist',
      department: 'Finance & Accounting',
      type: 'Full-Time',
      location: 'Manila Hub / Hybrid',
      shift: 'APAC Shift',
      description: 'Oversee end-to-end invoice validation, 3-way matching, payment scheduling, and collections workflows.',
      requirements: ['2+ years 3-way matching and invoice automation', 'High attention to detail and vendor communication'],
    },
    {
      id: 'it-systems-eng',
      title: 'Tier-2 IT Helpdesk & Systems Engineer',
      department: 'IT & Technical Support',
      type: 'Full-Time',
      location: 'Manila Hub',
      shift: 'US Shift',
      description: 'Provide proactive technical support, identity access management, and infrastructure monitoring.',
      requirements: ['Azure AD, Okta, Jira Service Management, Network Monitoring', 'Hands-on hardware & SaaS troubleshooting'],
    },
    {
      id: 'data-qa-lead',
      title: 'Data Processing & QA Specialist',
      department: 'Back-Office Operations',
      type: 'Full-Time',
      location: 'Regional Hub',
      shift: 'Flexible Shift',
      description: 'Maintain 99.8%+ accuracy on high-volume document indexing, database hygiene, and catalog moderation.',
      requirements: ['High-speed accurate indexing, OCR verification', 'Experience with large CRM/ERP datasets'],
    },
    {
      id: 'talent-acq-partner',
      title: 'HR & Talent Acquisition Specialist',
      department: 'HR & Recruitment',
      type: 'Full-Time',
      location: 'Manila Hub',
      shift: 'Day Shift',
      description: 'Source, screen, and place specialized offshore talent across our 7 core client pod disciplines.',
      requirements: ['Technical screening, ATS pipeline management', 'Demonstrated expertise in BPO talent acquisition'],
    },
  ],
};
