export const COMPANY = {
  name: 'Your Source Global',
  shortName: 'YSG',
  tagline: 'Sourcing. Solutions. Success.',
  headquarters: {
    address: 'FDRK7243 Compass Building, Al Shohada Road, Al Hamra Industrial Zone-FZ, Ras Al Khaimah, UAE',
    email: 'solutions@yoursourceglobal.com',
  },
  globalPresenceHeading: {
    eyebrow: 'Strategic International Footprint',
    badge: 'Multi-Region Delivery',
    title: 'Seamless Global Infrastructure Across Three Continents',
    subtitle: 'Connecting executive strategy in North America and Australia with dedicated, 24/7 high-capacity operational centers in the Philippines.',
  },
  presence: [
    {
      country: 'Global Headquarters (UAE)',
      regionCode: 'UAE',
      city: 'Ras Al Khaimah',
      role: 'Corporate Headquarters & Strategic Governance',
      focus: 'Global corporate oversight, international commercial agreements, enterprise governance, and global partnership coordination.',
      timezone: 'GST (UTC+4) Global Alignment',
      coverage: 'Executive Management & Client Inquiries',
      address: 'FDRK7243 Compass Building, Al Shohada Road, Al Hamra Industrial Zone-FZ, Ras Al Khaimah, UAE',
      phone: '+971 (0) 7 204 1111',
      email: 'solutions@yoursourceglobal.com',
      coordinates: { x: 55, y: 35 },
      capabilities: ['Corporate Governance', 'Global Operations Oversight', 'International Contracts & Compliance'],
    },
    {
      country: 'United States & Americas',
      regionCode: 'US',
      city: 'North America Client Hub',
      role: 'Executive Management & Client Strategy',
      focus: 'Enterprise account governance, contract structuring, executive sponsorship, and North American SLA management.',
      timezone: 'EST / CST / PST Overlap',
      coverage: 'Business Hours & Dedicated Escalations',
      address: 'North America Enterprise Hub',
      phone: '+1 (800) 555-0199',
      email: 'us@yoursourceglobal.com',
      coordinates: { x: 22, y: 38 },
      capabilities: ['Executive Account Management', 'Client Strategy & Onboarding', 'Contract & Governance SLA'],
    },
    {
      country: 'Philippines Delivery Hub',
      regionCode: 'PH',
      city: 'Manila & Regional Delivery Centers',
      role: '24/7 Dedicated Operational Delivery Hubs',
      focus: 'High-volume production facilities housing dedicated talent pods across all 7 core BPO service lines.',
      timezone: '24/7/365 Continuous Shifts',
      coverage: 'Round-The-Clock Global Delivery',
      address: 'Manila Delivery Center, Philippines',
      phone: '+63 2 8888 0199',
      email: 'operations@yoursourceglobal.com',
      coordinates: { x: 79, y: 52 },
      capabilities: ['24/7 Multilingual Support', 'Dedicated Pod Facilities', 'Redundant Power & High-Speed Fiber'],
    },
  ],
};
