export const COMPANY = {
  name: 'Your Source Global',
  shortName: 'YSG',
  tagline: 'Sourcing. Solutions. Success.',
  globalPresenceHeading: {
    eyebrow: 'Strategic International Footprint',
    badge: '[CONFIRM ADDRESS]',
    title: 'Seamless Global Infrastructure Across Three Continents',
    subtitle: 'Connecting executive strategy in North America and Australia with dedicated, 24/7 high-capacity operational centers in the Philippines.',
  },
  presence: [
    {
      country: 'United States',
      regionCode: 'US',
      city: 'North America Hub',
      role: 'Executive Management & Client Strategy',
      focus: 'Enterprise account governance, contract structuring, executive sponsorship, and North American SLA management.',
      timezone: 'EST / CST / PST Overlap',
      coverage: 'Business Hours & Dedicated Escalations',
      address: '[CONFIRM ADDRESS]',
      phone: '[CONFIRM PHONE]',
      email: 'us@yoursourceglobal.com',
      coordinates: { x: 22, y: 38 },
      capabilities: ['Executive Account Management', 'Client Strategy & Onboarding', 'Contract & Governance SLA'],
    },
    {
      country: 'Australia',
      regionCode: 'AU',
      city: 'Asia-Pacific Regional Office',
      role: 'Regional Operations & Client Support',
      focus: 'Asia-Pacific client relationship management, operational oversight, and regional expansion alignment.',
      timezone: 'AEST / AEDT Real-Time Support',
      coverage: 'Direct Business Hours & Account Care',
      address: '[CONFIRM ADDRESS]',
      phone: '[CONFIRM PHONE]',
      email: 'au@yoursourceglobal.com',
      coordinates: { x: 84, y: 78 },
      capabilities: ['APAC Client Partnerships', 'Regional Operational Advisory', 'Timezone-Aligned Coordination'],
    },
    {
      country: 'Philippines',
      regionCode: 'PH',
      city: 'Manila & Regional Delivery Centers',
      role: '24/7 Dedicated Operational Delivery Hubs',
      focus: 'High-volume production facilities housing dedicated talent pods across all 7 core BPO service lines.',
      timezone: '24/7/365 Continuous Shifts',
      coverage: 'Round-The-Clock Global Delivery',
      address: '[CONFIRM ADDRESS]',
      phone: '[CONFIRM PHONE]',
      email: 'operations@yoursourceglobal.com',
      coordinates: { x: 79, y: 52 },
      capabilities: ['24/7 Multilingual Support', 'Dedicated Pod Facilities', 'Redundant Power & High-Speed Fiber'],
    },
  ],
};
