export const INDUSTRIES_CONTENT = {
  eyebrow: 'Specialized Domain Expertise',
  badge: 'Enterprise Verticals',
  title: 'Tailored BPO Solutions Across Core Industry Sectors',
  subtitle: 'We deploy dedicated, domain-trained staffing pods calibrated to the regulatory, technical, and operational demands of your vertical.',
  industries: [
    {
      id: 'healthcare',
      name: 'Healthcare & Medical Support',
      description: 'HIPAA-compliant patient intake workflows, insurance verification, medical billing, and appointment coordination.',
      workflows: ['Patient Scheduling & Intake', 'Billing & Claims Reconciliation', 'Provider Credentialing'],
      icon: 'Activity',
      tag: 'HIPAA Compliant',
    },
    {
      id: 'finance',
      name: 'Financial Services & Fintech',
      description: 'High-accuracy bookkeeping, AP/AR ledger management, loan underwriting support, and fraud alert escalation.',
      workflows: ['AP/AR Processing', 'KYC & Document Verification', 'Financial Reconciliations'],
      icon: 'BadgeDollarSign',
      tag: 'Fintech & Banking',
    },
    {
      id: 'ecommerce',
      name: 'Retail & E-Commerce',
      description: '24/7 omnichannel customer care, order processing, marketplace inventory management, and dispute handling.',
      workflows: ['Omnichannel Support (Chat/Email)', 'Returns & Refund Operations', 'Catalog Data Management'],
      icon: 'ShoppingCart',
      tag: 'Retail & Brands',
    },
    {
      id: 'logistics',
      name: 'Logistics & Supply Chain',
      description: 'Real-time shipment tracking, freight dispatch coordination, customs documentation, and carrier support.',
      workflows: ['Freight Tracking & Tracing', 'Bill of Lading Entry', 'Carrier Communications'],
      icon: 'Truck',
      tag: 'Freight & Supply',
    },
    {
      id: 'real-estate',
      name: 'Real Estate & Property Management',
      description: 'Lease abstraction, tenant support desk, maintenance dispatch, and portfolio bookkeeping.',
      workflows: ['Lease Data Extraction', 'Tenant Work-Order Dispatch', 'Vendor Invoice Audits'],
      icon: 'Building',
      tag: 'Commercial & Residential',
    },
    {
      id: 'tech-saas',
      name: 'Technology & SaaS',
      description: 'Tier-1 and Tier-2 technical support, user onboarding assistance, CRM data hygiene, and QA ticket logging.',
      workflows: ['Tier-1/2 Helpdesk & Triage', 'User Onboarding & Setup', 'CRM & Pipeline Hygiene'],
      icon: 'Cpu',
      tag: 'SaaS & Software',
    },
  ],
};
