export const SERVICES_SECTION_HEADING = {
  eyebrow: 'Our 7 Specialized Disciplines',
  title: 'Dedicated Offshore Capabilities Built for Precision',
  subtitle: 'End-to-end managed service pods deployed across core operational verticals, integrating natively with your internal workflows.',
};

export const SERVICES = [
  {
    id: 'finance-accounting',
    number: '01',
    title: 'Finance & Accounting',
    tagline: 'Precision Bookkeeping & GAAP Compliance',
    shortDescription: 'Full-cycle accounting operations, general ledger reconciliation, statutory reporting, and tax preparation support.',
    deliverables: [
      'General ledger maintenance & balance sheet reconciliation',
      'Monthly/quarterly financial close & management reporting',
      'Cash flow forecasting & budget variance analysis',
      'Audit preparation & multi-entity GAAP compliance',
    ],
    tools: ['QuickBooks', 'NetSuite', 'Xero', 'Sage Intacct', 'SAP'],
    icon: 'Calculator',
    stat: '100% GAAP / IFRS accuracy focus',
  },
  {
    id: 'ap-ar',
    number: '02',
    title: 'Accounts Payable / Receivable',
    tagline: 'End-to-End Cash Flow & Billing Automation',
    shortDescription: 'Streamlined invoice processing, 3-way matching, vendor dispute management, collections, and automated aging reports.',
    deliverables: [
      '3-way invoice matching & automated PO verification',
      'Vendor ledger reconciliation & payment batch scheduling',
      'Customer billing, credit control & aging ledger follow-up',
      'Dispute resolution & deduction tracking',
    ],
    tools: ['Bill.com', 'Tipalti', 'AvidXchange', 'Coupa', 'Stripe'],
    icon: 'Receipt',
    stat: '48hr typical invoice cycle time',
  },
  {
    id: 'customer-support',
    number: '03',
    title: 'Customer Support (24/7 Omnichannel)',
    tagline: 'High-Empathy Tier 1-3 Customer Care',
    shortDescription: 'Round-the-clock voice, live chat, email, and social care delivered by fluent, highly trained support specialists.',
    deliverables: [
      '24/7/365 Tier-1 triage, Tier-2 resolution & live chat support',
      'Inbound voice support & proactive outbound care',
      'Ticketing escalation workflows & CSAT / NPS tracking',
      'Knowledge base authoring & community management',
    ],
    tools: ['Zendesk', 'Freshdesk', 'Intercom', 'Salesforce Service Cloud', 'Gorgias'],
    icon: 'Headset',
    stat: '95%+ First-Contact Resolution Target',
  },
  {
    id: 'data-processing',
    number: '04',
    title: 'Data Processing & Management',
    tagline: 'High-Volume Digitization & Quality Assurance',
    shortDescription: 'High-throughput data extraction, document indexing, database hygiene, OCR validation, and structured catalog tagging.',
    deliverables: [
      'High-volume document indexing, OCR review & data cleansing',
      'Database enrichment, deduplication & normalization',
      'Product catalog data entry, taxonomy & attribute tagging',
      'Forms verification & digital archive management',
    ],
    tools: ['AirTable', 'PostgreSQL', 'HubSpot', 'Alteryx', 'Excel Pro'],
    icon: 'Database',
    stat: '99.9% data verification accuracy',
  },
  {
    id: 'back-office',
    number: '05',
    title: 'Back-Office Operations',
    tagline: 'Frictionless Workflow & Logistics Execution',
    shortDescription: 'Order verification, logistics tracking, vendor onboarding, document processing, and executive administrative workflows.',
    deliverables: [
      'Order fulfillment validation & exception handling',
      'Freight & supply chain dispatch documentation',
      'Contract validation & document compliance checks',
      'Executive administrative assistance & scheduling',
    ],
    tools: ['Asana', 'Monday.com', 'ClickUp', 'Jira', 'SharePoint'],
    icon: 'Briefcase',
    stat: 'Streamlined multi-step workflows',
  },
  {
    id: 'it-support',
    number: '06',
    title: 'IT / Technical Support',
    tagline: 'Tier 1-2 Service Desk & Infrastructure Care',
    shortDescription: 'Enterprise helpdesk, user provisioning, access control, endpoint troubleshooting, and basic network monitoring.',
    deliverables: [
      'Tier 1 & 2 user support, ticket resolution & device setup',
      'SaaS access provisioning, deprovisioning & SSO setup',
      'Network uptime monitoring & alert escalation',
      'IT asset logging & security patch compliance tracking',
    ],
    tools: ['ServiceNow', 'Jira Service Management', 'Jitbit', 'Okta', 'Microsoft 365 Admin'],
    icon: 'Server',
    stat: '<15 min critical ticket response SLA',
  },
  {
    id: 'hr-recruitment',
    number: '07',
    title: 'HR & Recruitment Support',
    tagline: 'End-to-End Talent Sourcing & HR Administration',
    shortDescription: 'Candidate sourcing, resume screening, interview scheduling, employee record keeping, and payroll calculations.',
    deliverables: [
      'Talent pipeline sourcing & candidate pre-screening',
      'Interview coordination & candidate communications',
      'Employee records management & compliance documentation',
      'Timesheet validation & payroll computation support',
    ],
    tools: ['Workday', 'BambooHR', 'Greenhouse', 'Lever', 'Gusto'],
    icon: 'Users',
    stat: 'Faster time-to-hire pipelines',
  },
];
